### ISSUE TITLE
[Feature Request] Add a model for the classic API category record

### ISSUE THREAD

**Issue by Honestpuck** [macadmins/jamf-pro-sdk-python#12]
In a similar fashion to other models such as `classic.computer_groups` there is a need for a model for `classic.categories`

### Proposal

```
>>> categories = client.classic_api.list_all_categories()
>>> len(categories)
4
>>> type(categories[0])
<class 'jamf_pro_sdk.models.classic.categories.CategoriesItem'>
>>> for c in categories:
...   print(c.name)
...
Enrolment
Applications
Security
Tools
```

### Additional Details

I actually wanted to add a model for policies but thought I would start with a simpler model, so categories.

 (This project is a stretch for my python skills. We will see how I go.)

**Comment by Honestpuck** [comment]
Please assign it to me if it's acceptable :)

**Comment by brysontyrrell** [comment]
@Honestpuck If you want to take a stab at it do a fork and open a PR!

**Comment by Honestpuck** [comment]
Done :)
