### ISSUE TITLE
[Bug] send_mdm_command_preview broken?

### ISSUE THREAD

**Issue by jausmus-wayspring** [macadmins/jamf-pro-sdk-python#16]
When I run the send_mdm_command_preview with a UUID and a command, I get a pydantic.error_wrappers.ValidationError

### Steps to Reproduce

```
from jamf_pro_sdk import JamfProClient
from jamf_pro_sdk.clients import auth
from jamf_pro_sdk.models.pro.mdm import LogOutUserCommand

client = JamfProClient(
    server="*.jamfcloud.com",
    credentials=auth.ApiClientCredentialsProvider(
        client_id="",
        client_secret=""
    )
)

logout_user = client.pro_api.send_mdm_command_preview(
    management_ids=[""],
    command=LogOutUserCommand
)

```

All empty quotes have valid values.

### Expected Result

The MDM command is sent successfully.

### Actual Result

```
Traceback (most recent call last):
  File "/Users/jasonausmus/repos/wayspring-jamf/auth.py", line 14, in <module>
    logout_user = client.pro_api.send_mdm_command_preview(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonausmus/.local/share/virtualenvs/wayspring-jamf-_868w2GM/lib/python3.11/site-packages/jamf_pro_sdk/clients/pro_api/__init__.py", line 232, in send_mdm_command_preview
    data = SendMdmCommand(
           ^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for SendMdmCommand
commandData
  Discriminator 'commandType' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=commandType)
commandData
  value is not a valid dict (type=type_error.dict)
```

I'm not sure what I'm doing wrong here and I can't find any documented examples of using this method.

**Comment by brysontyrrell** [comment]
@jausmus-wayspring You need to instantiate the command object you're passing. Can you try:

```python
logout_user = client.pro_api.send_mdm_command_preview(
    management_ids=["<ID>"],
    command=LogOutUserCommand()
)
```

Few things I will start on related to this issue:
* The Pro API user guide needs a section on MDM commands with use cases/examples.
* The `send_mdm_command_preview` method needs example usage in the doc string. This is something that is going to be added across all API methods.
* The `LogOutUserCommand` model is missing from the Pro models doc page. I'll add it back in, and the models will include example usage like the API methods.

**Comment by jausmus-wayspring** [comment]
Thanks @brysontyrrell, instantiating it resolved the issue.
